version: '3.8'

services:
  mage:
    image: mageai/mageai:latest
    container_name: mage
    ports:
      - "6789:6789"
    volumes:
      - ./mage:/home/src
      - ./mage/.mage_data:/home/src/.mage_data
    environment:
      - USER_CODE_PATH=.
    command: mage start ${PROJECT_NAME:-clothing_classifier}

  model_service:
    build: ./model_service
    container_name: clothing_model_api
    ports:
      - "8000:3000"
