version: '3.8'

services:
  mage:
    image: mageai/mageai:latest
    container_name: mage
    ports:
      - "6789:6789"
    volumes:
      - ./volume:/home/src
      - ./volume/.mage_data:/home/src/.mage_data
      - ../model_service/model:/home/src/model_output 
    environment:
      - USER_CODE_PATH=.
    command: mage start ${PROJECT_NAME:-clothing_classifier}
